### ISSUE TITLE
It seemed that no file or directory in the “models"

### ISSUE THREAD

**Issue by Psyhang** [MIT-SUL-Team/global-sentiment#1]
Greatly thanks to your work!!
I am trying to run your code on my computer and trying to apply it to my research.
But when I ran the sentiment clf evaluator.ipynb
the following error occur: there is "No such file or directory: models/clf.pkl（emb.pkl）"
So, I checked the files and found no such file or directory in it.
Could you please send me a copy of them?
It will be greatly helpful!
Looking forward to your reply. 

Billy

**Comment by Kuailun** [comment]
Hi Billy,

Thank you for the question! 

Indeed, we didn't provide the trained classifier in our repository.
However, it is quite easy for you to replicate the entire procedure from training to testing following the instructions:

- Please go to data/labeled_data folder and download the corresponding labeled dataset
- Then, run setup_emb_clf.py script to build your own classifier

You will get the clf.pkl and emb.pkl.

**Comment by Psyhang** [comment]
Hi Kuailun,

Thanks for your reply.

I have downloaded the corresponding labeled dataset.

But I am still confused where I can get the following files:
 
data/labeled_data/train_ids.txt
data/labeled_data/test_ids.txt

I didn't find them in the download link.

Looking forward to your reply.
